use_frameworks!

target 'TrophyKit_Example_iOS' do
  platform :ios, '14.0'

  pod 'TrophyKit', :path => '../'

  target 'TrophyKit_Tests' do
    inherit! :search_paths
  end
end

target 'TrophyKit_Example_tvOS' do
  platform :tvos, '14.0'
  
  pod 'TrophyKit', :path => '../'
end
